### ISSUE TITLE
Language links broken

### ISSUE THREAD

**Issue by nathan-hekman** [ibm-cloud-docs/sdk-handbook#2]
https://cloud.ibm.com/docs/sdk-handbook?topic=sdk-handbook-go

![image](https://user-images.githubusercontent.com/6822736/106952126-4c1eb180-66f6-11eb-80f6-585c3887e816.png)

None of these links work. FYI @jenschlot

**Comment by christiancompton** [comment]
This issue has been addressed in both staging and production by @cjcarpen, and the changes are now live.  Closing as complete.

PR: https://github.ibm.com/cloud-docs/sdk-handbook/pull/14
https://cloud.ibm.com/docs/sdk-handbook?topic=sdk-handbook-java
